#Cargar un archivo en R

#list.files("./UCI HAR Dataset/test") #Qué hay en el directorio "./ es working directory. ~ es Masteralex  
#list.files("./UCI HAR Dataset/train")
#read.table
#data  <- read.csv(fileName )
#Número de filas: nrow(x_train)
# Nombre columnas: names(x_train)
# view (x_train) # ver en tablita formato gráfico
# colMeans(all) - #Media de todas las columnas
# sapply(all, mean) 
# sapply(all, sd)
# summary(all) 



# TEST: 
file <- "./UCI HAR Dataset/test/X_test.txt"
x_test <- read.table (file, sep="", header=FALSE)  # comando para leer un archivo
names(x_test)

file <- "./UCI HAR Dataset/test/y_test.txt"
y_test <- read.table (file, sep="", header=FALSE)  # comando para leer un archivo
#names(y_test)

file <- "./UCI HAR Dataset/test/y_test.txt"
y_test <- read.table (file, sep="", header=FALSE)  # comando para leer un archivo

file <- "./UCI HAR Dataset/test/subject_test.txt"
subject_test <-  read.table (file, sep="", header=FALSE)  # comando para leer un archivo
names(subject_test)[1] <- "subject"

# TRAIN: 
file <- "./UCI HAR Dataset/train/X_train.txt"
x_train <- read.table (file, sep="", header=FALSE)  # comando para leer un archivo
#names(x_train)

file <- "./UCI HAR Dataset/train/y_train.txt"
y_train <- read.table (file, sep="", header=FALSE)  # comando para leer un archivo
#names(y_train)

file <- "./UCI HAR Dataset/train/subject_train.txt"
subject_train <- read.table (file, sep="", header=FALSE)  # comando para leer un archivo
names(subject_train)[1] <- "subject"


#head(subject_train)
#names(x_test)

# Get Test and Train toguether
all <- rbind(x_test, x_train)


# Get mean and SD from data (all)
sapply(all, mean)
sapply(all, sd)

# Become one data set for test and train
all_y <- rbind(y_test, y_train)
all_subject <- rbind(subject_test, subject_train)


#nrow(all_subject)
#head(subject_test) 
#head(subject_train)

#nrow(all)
#nrow(all_y)

#names(all)



#list.files("./UCI HAR Dataset/test")
#read.table
#data  <- read.csv(fileName )
file <- "./UCI HAR Dataset/activity_labels.txt"
activity_labels <- read.table (file, sep="", header=FALSE)  # comando para leer un archivo
#names(activity_labels)

#activity_labels

#Renombrar nombres de columnas
names(activity_labels)[1] <- "activity_codes"
names(activity_labels)[2] <- "activity_labels"

names(all_y)[names(all_y)=="V1"] <- "activity_codes_en_y"
names(all_y)[names(all_y)=="V1"] <- "activity_codes_en_y"


#making a single data frame
all_with_x_y <- cbind(all_y,all)
#View(all_with_x_y)

#names(all_with_x_y)

all_with_x_y_labels <- merge(all_with_x_y, activity_labels, by.x="activity_codes_en_y", by.y="activity_codes")

all_with_x_y_labels_subjects <- cbind(all_subject, all_with_x_y_labels)

names(all_with_x_y_labels_subjects)


# Sorry for all this code. Couldn´t find the method to get mean massively.
average_subject <- aggregate( V1~subject+activity_labels, all_with_x_y_labels_subjects, mean ); names(average_subject)[3] <- "Mean"
avg_temp<-aggregate( V2~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V3~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V4~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V5~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V6~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V7~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V8~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V9~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V10~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V11~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V12~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V13~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V14~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V15~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V16~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V17~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V18~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V19~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V20~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V21~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V22~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V23~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V24~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V25~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V26~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V27~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V28~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V29~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V30~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V31~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V32~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V33~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V34~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V35~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V36~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V37~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V38~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V39~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V40~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V41~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V42~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V43~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V44~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V45~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V46~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V47~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V48~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V49~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V50~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V51~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V52~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V53~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V54~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V55~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V56~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V57~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V58~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V59~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V60~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V61~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V62~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V63~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V64~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V65~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V66~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V67~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V68~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V69~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V70~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V71~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V72~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V73~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V74~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V75~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V76~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V77~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V78~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V79~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V80~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V81~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V82~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V83~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V84~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V85~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V86~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V87~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V88~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V89~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V90~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V91~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V92~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V93~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V94~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V95~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V96~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V97~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V98~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V99~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V100~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V101~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V102~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V103~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V104~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V105~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V106~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V107~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V108~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V109~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V110~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V111~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V112~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V113~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V114~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V115~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V116~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V117~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V118~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V119~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V120~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V121~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V122~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V123~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V124~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V125~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V126~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V127~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V128~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V129~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V130~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V131~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V132~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V133~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V134~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V135~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V136~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V137~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V138~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V139~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V140~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V141~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V142~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V143~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V144~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V145~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V146~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V147~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V148~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V149~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V150~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V151~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V152~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V153~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V154~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V155~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V156~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V157~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V158~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V159~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V160~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V161~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V162~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V163~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V164~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V165~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V166~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V167~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V168~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V169~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V170~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V171~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V172~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V173~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V174~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V175~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V176~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V177~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V178~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V179~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V180~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V181~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V182~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V183~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V184~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V185~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V186~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V187~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V188~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V189~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V190~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V191~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V192~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V193~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V194~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V195~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V196~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V197~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V198~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V199~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V200~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V201~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V202~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V203~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V204~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V205~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V206~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V207~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V208~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V209~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V210~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V211~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V212~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V213~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V214~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V215~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V216~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V217~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V218~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V219~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V220~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V221~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V222~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V223~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V224~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V225~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V226~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V227~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V228~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V229~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V230~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V231~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V232~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V233~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V234~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V235~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V236~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V237~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V238~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V239~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V240~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V241~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V242~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V243~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V244~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V245~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V246~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V247~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V248~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V249~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V250~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V251~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V252~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V253~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V254~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V255~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V256~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V257~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V258~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V259~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V260~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V261~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V262~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V263~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V264~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V265~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V266~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V267~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V268~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V269~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V270~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V271~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V272~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V273~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V274~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V275~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V276~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V277~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V278~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V279~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V280~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V281~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V282~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V283~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V284~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V285~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V286~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V287~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V288~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V289~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V290~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V291~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V292~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V293~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V294~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V295~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V296~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V297~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V298~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V299~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V300~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V301~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V302~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V303~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V304~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V305~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V306~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V307~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V308~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V309~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V310~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V311~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V312~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V313~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V314~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V315~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V316~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V317~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V318~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V319~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V320~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V321~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V322~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V323~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V324~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V325~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V326~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V327~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V328~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V329~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V330~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V331~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V332~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V333~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V334~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V335~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V336~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V337~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V338~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V339~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V340~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V341~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V342~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V343~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V344~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V345~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V346~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V347~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V348~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V349~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V350~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V351~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V352~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V353~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V354~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V355~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V356~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V357~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V358~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V359~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V360~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V361~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V362~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V363~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V364~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V365~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V366~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V367~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V368~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V369~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V370~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V371~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V372~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V373~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V374~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V375~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V376~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V377~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V378~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V379~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V380~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V381~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V382~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V383~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V384~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V385~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V386~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V387~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V388~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V389~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V390~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V391~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V392~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V393~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V394~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V395~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V396~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V397~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V398~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V399~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V400~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V401~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V402~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V403~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V404~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V405~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V406~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V407~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V408~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V409~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V410~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V411~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V412~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V413~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V414~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V415~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V416~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V417~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V418~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V419~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V420~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V421~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V422~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V423~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V424~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V425~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V426~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V427~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V428~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V429~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V430~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V431~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V432~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V433~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V434~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V435~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V436~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V437~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V438~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V439~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V440~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V441~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V442~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V443~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V444~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V445~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V446~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V447~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V448~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V449~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V450~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V451~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V452~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V453~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V454~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V455~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V456~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V457~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V458~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V459~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V460~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V461~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V462~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V463~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V464~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V465~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V466~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V467~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V468~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V469~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V470~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V471~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V472~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V473~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V474~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V475~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V476~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V477~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V478~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V479~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V480~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V481~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V482~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V483~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V484~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V485~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V486~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V487~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V488~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V489~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V490~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V491~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V492~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V493~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V494~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V495~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V496~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V497~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V498~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V499~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V500~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V501~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V502~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V503~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V504~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V505~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V506~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V507~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V508~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V509~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V510~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V511~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V512~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V513~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V514~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V515~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V516~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V517~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V518~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V519~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V520~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V521~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V522~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V523~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V524~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V525~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V526~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V527~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V528~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V529~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V530~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V531~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V532~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V533~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V534~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V535~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V536~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V537~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V538~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V539~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V540~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V541~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V542~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V543~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V544~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V545~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V546~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V547~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V548~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V549~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V550~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V551~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V552~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V553~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V554~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V555~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V556~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V557~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V558~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V559~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V560~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)
avg_temp<-aggregate( V561~subject+activity_labels, all_with_x_y_labels_subjects, mean ) ;names(avg_temp)[3] <- "Mean" ;average_subject <- rbind(average_subject, avg_temp)




write.table(average_subject, "average_subject.txt", sep="\t") 
